### ISSUE TITLE
Guru Galaxy's (L'1011 Tristar) back engine is not drawn well 

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#115]
The title say's it all. The Guru Galaxy's back engine resembles the DC-10/MD-11 (which in-game are named LB-10, respectively LB-11) engine, instead of the back engine of the L'1011 Tristar, which the Galaxy resembles.

![IMG_20240209_202635](https://github.com/zephyris/opengfx2/assets/145707519/0d3631d8-8560-48c6-bd31-f4cf252d4d62)

In the photo, the aircraft on the left is the DC-10 and the one on the right is the Tristar.

Guru Galaxy's back engine should resemble the Darwin 100's (Boeing 727) engine instead.

**Comment by zephyris** [comment]
Thanks for the report, but I'm afraid this is an OpenTTD limitation/inaccuracy. The base aircraft have hard-coded sharing of sprites, and the LB-10/LB-11/Guru Galaxy all share the same graphics, right back to Transport Tycoon. You can see this in the original graphics:
![image](https://github.com/zephyris/opengfx2/assets/2762690/7414596e-1a6b-481c-b1ae-e34881363667)
I can't fix it in the base set, sorry!

**Comment by Rapha493** [comment]
> Thanks for the report, but I'm afraid this is an OpenTTD limitation/inaccuracy. The base aircraft have hard-coded sharing of sprites, and the LB-10/LB-11/Guru Galaxy all share the same graphics, right back to Transport Tycoon. You can see this in the original graphics: ![image](https://private-user-images.githubusercontent.com/2762690/303786982-7414596e-1a6b-481c-b1ae-e34881363667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDczMDUsIm5iZiI6MTcwNzU0NzAwNSwicGF0aCI6Ii8yNzYyNjkwLzMwMzc4Njk4Mi03NDE0NTk2ZS0xYTZiLTQ4MWMtYjFhZS1lMzQ4ODEzNjM2NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMDYzNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEyODk4MTQwN2EzOWUxZjdiNTMwYmQyNzVjNzcwNjljNDNmNzEyNWY5NGJjMjA1ZTNiNmE3M2E4ZjQ3MGIzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kihm75YWWARrk1WH_Nlrygg1nUFM6YpCbsYNfBwEd8g) I can't fix it in the base set, sorry!

Well, that's just sad. That's also why every Airbus(airtaxi) plus some of the boeings(Darwin) looks the same?

**Comment by zephyris** [comment]
Yup. You need newgrfs for more accurate plane appearances. There's a vague chance of an OpenGFX2+ Aeroplanes newgrf at some point, but not for a long time!
