### ISSUE TITLE
Flickering textures of crashed aircraft

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#116]
![Screenshot_2024-02-13-23-09-27-972_org openttd sdl](https://github.com/zephyris/opengfx2/assets/145707519/e764e427-dc48-4e28-9ab9-bf7b96037ffe)

In this screenshot only half of the aircraft is visible

![Screenshot_2024-02-13-23-12-13-728_org openttd sdl](https://github.com/zephyris/opengfx2/assets/145707519/6862b608-2c64-44c7-b93e-d1fcb6c6d50e)

This screenshot is after I moved the camera a bit.

**Comment by zephyris** [comment]
I suspect that this is an OpenTTD bug. The sprite looks correct, and isn't oversized for an aircraft sprite. Flickering tends to happen when the sprite is too big for the in-game bounding box for the object.

What's happening in this screenshot? It's weird to me that there's a crashed plane but no airport!

**Comment by Rapha493** [comment]
> I suspect that this is an OpenTTD bug. The sprite looks correct, and isn't oversized for an aircraft sprite. Flickering tends to happen when the sprite is too big for the in-game bounding box for the object.
> 
> What's happening in this screenshot? It's weird to me that there's a crashed plane but no airport!

Basically what I did is that I took an aircraft for, let's say a "flight test", in which i made it take off and delete the airport. After a month, the plane ran out of fuel, crashed and I observed that it's texture is flickering (like the industry textures in toyland if you remember), and that's kinda it.

**Comment by zephyris** [comment]
Huh, didn't even know that was possible!

Anyway, I'm going to close this as a not graphics issue, perhaps worth posting as a bug for. OpenTTD. I suspect it's a not very solveable problem as a plane could crash in weird places like on a building where it'll end up facing funny sprite sorting problems.

**Comment by Rapha493** [comment]
> Huh, didn't even know that was possible!
> 
> Anyway, I'm going to close this as a not graphics issue, perhaps worth posting as a bug for. OpenTTD. I suspect it's a not very solveable problem as a plane could crash in weird places like on a building where it'll end up facing funny sprite sorting problems.

Thanks for the advice with reporting it directly for Openttd. I did that.
 I thought it was a graphics problem because the airplane didn't have a new texture and probably could interfere with the ground. You never know...
