### ISSUE TITLE
River edges sometimes have animated water showing thru

### ISSUE THREAD

**Issue by Brickblock1** [zephyris/opengfx2#19]

**Comment by zephyris** [comment]
A screenshot would be super useful here - I'm not sure where you're seeing this... Any particular climate/zoom level/slopes?

**Comment by Brickblock1** [comment]
![image](https://github.com/zephyris/opengfx2/assets/100433052/8089fa6a-4c93-46c5-aec7-39559bdaa641)
probably in the other climates as well

**Comment by Brickblock1** [comment]
seems that these sprites are also wrong since they aren't on the coast
![image](https://github.com/zephyris/opengfx2/assets/100433052/6ea39a76-0ce0-475c-83c8-acfd43530150)
they don't have animation either

**Comment by zephyris** [comment]
Coastlines not animated is a known issue... I don't think there is any way around the coastlines showing on zero height tiles when not next to water - unless you know about some nml magic that I don't!

**Comment by Brickblock1** [comment]
I am not sure they should even have coastline tbh since I can't think of a case where that would make sense. It is probably also worth taking a look at this relevant issue https://github.com/OpenTTD/OpenTTD/issues/10218

**Comment by zephyris** [comment]
Tracked the stray pixels down - the tile shape is a 25% nearest neighbour resize of the 256px sprites. That gives stray pixels as the 256 tile shapes were designed as a composite of the appropriate 64 tiles, rather than ensuring nearest neighbour rescaling would work.
