### ISSUE TITLE
Tropical ground issue on normal zoom level

### ISSUE THREAD

**Issue by stormcone** [zephyris/opengfx2#26]
There is an issue on tropical climate, when a house is on a specific slope type on normal zoom level, or on zoom out. On 2x or 4x zoom there is no issue.

![tropical_house_issue](https://github.com/zephyris/opengfx2/assets/48624099/b557b479-47a0-4a8b-becd-d7c3ee3b738a)

![tropical_house_issue_2](https://github.com/zephyris/opengfx2/assets/48624099/8d4a0df4-f1bc-4db7-9dcc-51c3fd4b0989)

![tropical_house_issue_3](https://github.com/zephyris/opengfx2/assets/48624099/d9e40e81-6e99-4b12-8bbf-b1c88a26b5e0)

**Comment by zephyris** [comment]
Huh, very weird! Is this, the "Classic" 8bpp 1x zoom or the "High Def" 32bpp 4x zoom, and what version?

I don't see this in my development version. I've been working on parameter control of foundation style, so may have accidentally fixed the bug. But, it'd be good to know _how_ I fixed the bug to avoid it in the future.

**Comment by stormcone** [comment]
It is the "High Def" variant. (The sprite aligner window shows it on the top. ;) ),
downloaded from here: https://github.com/zephyris/opengfx2/releases/tag/v0.1. (So I think it is v0.1, however the .obg says version = 0. :P )

**Comment by zephyris** [comment]
The issue was the 32bpp 1x zoom sprites were pointing to the 4x zoom spritesheet, will be fixed soon!
