### ISSUE TITLE
Foundation glitch while building

### ISSUE THREAD

**Issue by frosch123** [zephyris/opengfx2#27]
Foundation walls look different in various compositions: There are 3 different walls on the middle tile here, depending on adjacent tiles:
![image](https://github.com/zephyris/opengfx2/assets/23150643/ad410897-60ff-49d9-a2d9-7ee93eb500e7)
The sprite changes while building the neighbouring tiles, which glitches and looks weird.

**Comment by zephyris** [comment]
![opengfx2_bugbaregroundteraform](https://github.com/zephyris/opengfx2/assets/2762690/9c32de22-fef6-43e5-bf9f-3d6411419b7f)
Similar issue occurs when terraforming. The flat regions of tiles with one corner raised do not match the flat tile - if you raise and lower a tile the flat region glitches slightly.

Planned fix is some python to essentially copy/paste regions which should be identical within a sprite sheet. Should be run _after_ 8bpp conversion, to avoid differences in dithering from 32bpp->8bpp conversion. Can be applied to foundation, ground tile and jittery dither in animations (#25).

**Comment by zephyris** [comment]
I've decided not to try to fixing the bare earth ground glitchyness for now... Foundations are done though.
