### ISSUE TITLE
Tubular bridges missing half of one support

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [zephyris/opengfx2#31]
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/e090a9dc-629c-4e36-972b-d3d0f27d0698)
Support is missing on all tubular bridges, including Toyland.

**Comment by zephyris** [comment]
I can't quite work this one out... the source sprites look correct (leg sprite is present): https://github.com/zephyris/opengfx2/blob/146878ab80dcc677b25354189ae19e7500fe32e5/graphics/bridges/64/bridge_tubular_toyland_32bpp.png
Might be a coding issue, but I can't spot an issue.

**Comment by DefinitelyNotRau117** [comment]
This problem is present in other baseset/newgrf to varying degrees. 
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/20e209a3-3b80-46ea-870e-7f42429fe72f)
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/551be062-bb8a-444c-8a7d-2b207ae491d1)

OpenGFX and BRIX overcame it by using a single «cube» supports.
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/969985f0-a079-48a9-a189-0df715e75e33)
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/1741fab0-09a7-4076-b37c-ad1af84a684b)

But in the newgrf «total bridge replacement set» the problem is solved by using a double support without a gap.
Will it be possible to apply this solution to baseset?
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/e78aa859-cac7-457c-a85a-2597eb5d9358)
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/216ee165-6a72-42e9-9c3d-34d20fd14487)

**Comment by zephyris** [comment]
OK, thanks, that clarifies things. I can double the width of that specific sprite, but this evidence says this is actually an OpenTTD bug, right? I wonder if this is original TTD behaviour...
