### ISSUE TITLE
Toyland tunnels use temperate sprites

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [zephyris/opengfx2#32]
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/c193665d-2678-403c-8cbf-6f117406cb67)

**Comment by zephyris** [comment]
Good catch. I think the same issue will apply to toyland level crossings.

**Comment by DefinitelyNotRau117** [comment]
> Good catch. I think the same issue will apply to toyland level crossings.

Yes, sorry, forgot to reply.
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/86fefa5a-46a7-4d44-afd9-93e0c3b4217b)

v0.2. The tunnels are fixed, but the crossings remain temperate.
