### ISSUE TITLE
Readme and changelog not viewable in game.

### ISSUE THREAD

**Issue by PeterN** [zephyris/opengfx2#41]
OpenGFX had Readme and Changelog available to view in game:

![image](https://github.com/zephyris/opengfx2/assets/639850/8d93b6a2-6077-43d1-a22c-cf1f30998c74)

With OpenGFX2, these are not available, so it's harder to find what version I have:

![image](https://github.com/zephyris/opengfx2/assets/639850/7eb27c9d-70cc-4dbf-9db0-5b775f719221)

**Comment by zephyris** [comment]
I'd like to, but I don't know how to! Or I'm doing something dumb. Looking at the OpenGFX .tar it simply includes a readme.txt, changelog.txt and license.txt. Including those in the OpenGFX2 tars doesn't seem to work.

![opengfx2_readme](https://github.com/zephyris/opengfx2/assets/2762690/8b4136b2-1a5d-44eb-b4e6-dbd1b6e98a7a)

I'm assuming you got it from BaNaNaS, which must package the license itself?
