### ISSUE TITLE
OpenTTD identifies ogfx2 v0.1 as newer 

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [zephyris/opengfx2#44]
If the game sees the old and new versions of ogfx2, it identifies v0.1 as the newer one and uses it, which makes all previous bugs visible. The baseset is marked as downloaded in the online content.

![изображение](https://github.com/zephyris/opengfx2/assets/115672237/0b30586f-4d87-44cc-9bfc-7e051d2e0715)

If you delete/rename the old archive, the game will use v0.2.

![изображение](https://github.com/zephyris/opengfx2/assets/115672237/380e5717-7fde-4f26-949c-d83b90a74d1a)

Not sure if this can be fixed on your end, but it's at least worth mentioning it in the information in the online content.

**Comment by zephyris** [comment]
Oh, that's really weird and annoying. I wonder why? This will take some testing...
