### ISSUE TITLE
Suggestion: make crossings for maglevs more realistic

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [zephyris/opengfx2#45]
Crossing for ordinary rails is very easy to do in real life, it does not require special technological tricks. This is also well rendered in the game. Just road, just rails.
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/920cadfe-c404-400f-bc21-873fb258d569)

However, the maglev in the game uses the Japanese version - a "channel" at ground level, inside which there is a part of the train. This is not so noticeable in the game - technically, any rails in the game are completely flat.
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/39026140-6edc-4a8e-a2af-b897ef7dd815)

The current closed railway crossing creates a problem for the train - a wall inside the “channel”. The open crossing can be left in its current form. 

![изображение](https://github.com/zephyris/opengfx2/assets/115672237/060a3d7b-53c4-47fa-8269-d6869ac16ec4)
_If you enable “show reserved paths”, the illusion of an open crossing will appear, but this is just a small flaw._
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/c392e3dd-013d-48dc-92c2-cbbf873b5089)

**Well, the suggestion is** to change the open maglev crossing sprite so that the train can pass through.
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/319093db-5d96-49a3-9c3f-ec6d5878d0fe)

I hope the problem and explanation will be clearer in pictures (=

**Comment by zephyris** [comment]
Very clear description! The block in the level crossing is supposed to be something like this... but needs more work...
