### ISSUE TITLE
Buldozer icon missing

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#47]
The picture shows it all
![Screenshot_2023-09-21-23-16-23-586_org openttd sdl](https://github.com/zephyris/opengfx2/assets/145707519/47e5bd8b-4e5a-4b65-9860-93449dc3af43)

**Comment by DefinitelyNotRau117** [comment]
Missing on x2+ interface zoom
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/d0ae2d89-5a60-412d-89fa-45d72ab1d6fd)
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/3c40ea41-7a5e-4626-9711-56cb2569aa09)
