### ISSUE TITLE
Some Maglev sprites are reverted

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#48]
Two of the maglev tracks in the building tab are reverted.

**Comment by DefinitelyNotRau117** [comment]
More precisely, buttons 3 and 4, (west - east and northWest - southEast tracks)
And, judging by the sprite aligner, it’s enough to simply swap sprites # 1262 and 1261
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/49736a45-a52e-42a2-ac28-80f6613577b7)

**Comment by zephyris** [comment]
This is a bonkers OpenTTD weirdism. For rail and monorail the sprites are in order left to right (1251, 1252, 1253, 1254 and 1255, 1256, 1257, 1258 respectively). For maglev they're 1259, 1560, 1262, 1261(!).
