### ISSUE TITLE
River banks always temperate green when OpenGFX2 Settings not loaded

### ISSUE THREAD

**Issue by 2TallTyler** [zephyris/opengfx2#54]
Version: OpenGFX2 Classic

![rivers](https://github.com/zephyris/opengfx2/assets/55058389/3caaba26-1982-4d16-b66e-1ebe9c0aa196)

When OpenGFX2 Settings is not used in the game, river banks always use the temperate grass colour, even in sub-arctic and sub-tropic.

**Comment by zephyris** [comment]
Actual bug is arctic uses temperate, tropical uses arctic and toyland uses temperate... Hmm.

**Comment by 2TallTyler** [comment]
Off-by-one error?
