### ISSUE TITLE
Sloped rock tiles have miscolored ground underlay

### ISSUE THREAD

**Issue by therealbungus** [zephyris/opengfx2#59]
Some rock tiles have the wrong color ground beneath them, this is alpine for example.

It looks like some of the diagonal sloped ones are okay while the rest have the wrong color.

![rock1](https://github.com/zephyris/opengfx2/assets/449237/63549274-a9f7-45ea-9717-ed825f4f7896)

![rock2](https://github.com/zephyris/opengfx2/assets/449237/518b9358-e743-4b57-9cd2-0ee72a03d41c)

**Comment by zephyris** [comment]
Confirmed... Weird one that. I use an overlay layer with shades of gray to shade the grass texture - somehow managed to have a greenish hue instead for _only_ a couple of arctic rock slopes.
