### ISSUE TITLE
Palms on the roads in Sub-Arctic

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#69]
![Uploading Screenshot_2023-11-26-22-01-18-242_org.openttd.sdl.jpg…]()

**Comment by zephyris** [comment]
Your screenshot didn't work... But I assume you're seeing palm trees in the arctic climate in v0.3? I think I've already addressed this bug, keep an eye out for the next release.

**Comment by zephyris** [comment]
I've tested OpenGFX2 v0.4 in OpenTTD 13.4 and can't replicate this. I'll mark as closed, but feel free to post another bug report if you still see issues.
