### ISSUE TITLE
The "Sort By" button has a gap below it in the company vehicle list window

### ISSUE THREAD

**Issue by J-PIE-314** [zephyris/opengfx2#72]
Operating System: Windows 64-bit
Release: OpenGFX2 v0.3

Issue:

The "Sort By" button has a gap below it in the company vehicle list window.

Steps to reproduce:

1. With OpenGFX2 enabled, open a game.
2. Click on any of the vehicle icons on the top of the screen. The window that appears will exhibit the gap.

Below are photos comparing OpenGFX2 v0.3 to OpenGFX.

OpenGFX2 v0.3 issue:
![opengfx2 window gap 1](https://github.com/zephyris/opengfx2/assets/80489909/debf8c1a-3cd1-4a0d-ad2b-dccb72117c05)
OpenGFX no issue:
![opengfx2 window gap 2](https://github.com/zephyris/opengfx2/assets/80489909/f407cb98-13fa-493a-9d71-13381fc47501)

**Comment by zephyris** [comment]
Thanks - I'd seen this issue too. I believe this is an OpenTTD bug that will be fixed in v14. In the meantime you can try an nightly and see if it is fixed.
