### ISSUE TITLE
Forest industries have misaligned tree bases in 4x zoom

### ISSUE THREAD

**Issue by J-PIE-314** [zephyris/opengfx2#74]
Operating System: Windows 64-bit
Release: OpenGFX2 v0.4

Issue:

When zoomed in to see the 32-bit images, the black tree bases on the tiles below forest industries are not hidden by all of the tree's trunks.

Screenshot:

![opengfx2 tree alignment issue](https://github.com/zephyris/opengfx2/assets/80489909/926b75b5-a67a-49a5-b33b-08acde2a93da)

**Comment by zephyris** [comment]
... and I should use the temperate grass as the basis of temperate (non-snowy) forests!
