### ISSUE TITLE
Feature request: Show growing space for street trees

### ISSUE THREAD

**Issue by J-PIE-314** [zephyris/opengfx2#75]
Being a tree nerd, I couldn't help but notice that the street trees are growing in concrete. Could there perhaps be a future update that shows around the tree trunk, a square shaped gap in the sidewalk?

Screenshot:
![opengfx2 trees growing in concrete](https://github.com/zephyris/opengfx2/assets/80489909/1e0c9726-aab2-4780-9873-0ac66e565a29)

**Comment by zephyris** [comment]
Nice concept, I think it works well. The alignment on slopes is an OpenTTD limitation (but, would probably be adjustable in the OpenTTD source code, without _too_ much resistance!). I'm very happy to include these sprites if you make them.

I wonder if the base of the palm tree will be too far to the left?

**Comment by zephyris** [comment]
If you make the little ground circle on its own I'll add it as a layer in the original layered sources. Easy for me to then to tweak trunk width or palm tree style later. Does that sound OK?
