### ISSUE TITLE
Sprites 1448 to 1453 have white pixels and are also missing pixels on some sides.

### ISSUE THREAD

**Issue by PeterN** [zephyris/opengfx2#81]
Samples of issues (not necessarily all cases)

![image](https://github.com/zephyris/opengfx2/assets/639850/75e9362f-e46f-4e4e-b8dc-eb5425ae463a)

e.g.top corner is rounded off, maybe a style choice though:

![image](https://github.com/zephyris/opengfx2/assets/639850/8812b2c8-21e4-4471-901d-0d356f58e9b8)

e.g. bottom corner is cropped off: 

![image](https://github.com/zephyris/opengfx2/assets/639850/d3815599-6fa3-47ec-8092-4dfdd9e874cb)

**Comment by zephyris** [comment]
The rounded corners are graphics laziness, and will be corrected later. The white bars are a definite bug translating the sprite chopping code from 1x to 4x!
