### ISSUE TITLE
Sprouts visible below rubber plantation when in 4x and 2x zoom

### ISSUE THREAD

**Issue by J-PIE-314** [zephyris/opengfx2#85]
Operating System: Windows 64-bit
Release: OpenGFX2 v0.4

Issue:

Green sprouts are visible on the terrain tiles below rubber plantations.
I believe this to be an unintended detail introduced by commit 0b86b6363b251e8958e52fcf2478c316c9c4360c .

Screenshot:

![opengfx2 rubber plantation issue](https://github.com/zephyris/opengfx2/assets/80489909/6bcb280e-2b61-4d54-b8e5-bd3a66331a82)

**Comment by zephyris** [comment]
I'm calling this a FIRS(?) bug I'm afraid - looks like it uses one of the default trees (which comes with rocks and mini-plants at 4x) and the _second_ stage farm field (which I think reasonably can have little shoots).
