### ISSUE TITLE
Corners missing on terrain tiles below forest industries and rubber plantation industries

### ISSUE THREAD

**Issue by J-PIE-314** [zephyris/opengfx2#86]
Operating System: Windows 64-bit
Release: OpenGFX2 v0.4

Issue:

The bottom corner is missing from terrain tiles below forest industries and rubber plantation industries.

Screenshots:

![opengfx2 forest corner issue 3](https://github.com/zephyris/opengfx2/assets/80489909/ebe5aa73-e9f9-4bd8-91bb-3f0dc52da5c9)
![opengfx2 forest corner issue 2](https://github.com/zephyris/opengfx2/assets/80489909/023f2135-21fc-413a-8616-824f70bc19d8)
![opengfx2 forest corner issue 1](https://github.com/zephyris/opengfx2/assets/80489909/9366b316-f442-4ed5-9173-24d1eb508293)

**Comment by zephyris** [comment]
This is related to #76. Ground tile sprite positioning and Y offset is complicated...

**Comment by zephyris** [comment]
Fixed in 79eb8ec
