### ISSUE TITLE
End game newspaper text doesn't fit

### ISSUE THREAD

**Issue by 2TallTyler** [zephyris/opengfx2#87]
![endgame](https://github.com/zephyris/opengfx2/assets/55058389/a19fee9a-a97a-42ad-9983-4ab6199b11b3)

In OpenGFX2 Classic, the text in the end game newspaper doesn't fit above the photograph and divider line.

I checked interface scale settings and it happens on 1x and 2x...haven't tried others. It does not occur with TTD or original OpenGFX, so it seems to be a base set problem.

I've never seen the perfect score screen, so I have not checked that. 😛

**Comment by zephyris** [comment]
I went back to original SVG sources for these sprites, I guess there was a bitmap fix at some point in OpenGFX... I'll be updating to fit better on the brown background too.
