### ISSUE TITLE
Bug: Locomotive sprites are cut off on the right side

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [zephyris/opengfx2#91]
Perhaps the sprites are cut off because they are misaligned in source files

![изображение](https://github.com/zephyris/opengfx2/assets/115672237/0c88fe30-6b89-4cfe-8930-9ec3a13ebd14)

In opengfx(1) the trains are located much higher - the wheels are at the level of the rails

![изображение](https://github.com/zephyris/opengfx2/assets/115672237/aba12667-63a1-485d-82cb-b9d58c65e75f)

There are also defective pixels on the trains (not all are shown in the picture)
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/f0580cec-62f7-4509-90e3-d9a4c3f45e23)

**Comment by zephyris** [comment]
3 issues here:

1. Vertical alignment in the horizontal view.
This is arguably an OpenGFX(1) bug. The horizontal sprites are positioned too high, and makes the buy menu glitchy. IMO, a player is more likely to notice misalignments in the buy menu than trains not quite sitting on diagonal rails.
![image](https://github.com/zephyris/opengfx2/assets/2762690/a14be109-06b0-4e40-909d-0abd33f2cea9)

2. Front/back cutoff in the horizontal view.
Seems just to affect monolev engines, except SH125 (which has been updated now anyway). Something to look into.

3. Defective pixels
4. Yeah, there's a weird palette conversion bug somewhere, I'll look into it.

**Comment by DefinitelyNotRau117** [comment]
>1  This is arguably an OpenGFX(1) bug.

Does this mean that the trains will remain in current position relative to the rails?

In newgrf you can set different sprites for the menu and the world, this way it is possible to align the sprites in both ways. If it will not work out for baseset, in my opinion it is better to align trains by the world.

Moreover, the problem with the menu can be circumvented by using a different font or interface size. Misaligned sprites can only be fixed by changing the source files and rebuilding the set.

_After all, the game is not about browsing through menus._

**Comment by zephyris** [comment]
The OpenGFX misalignment (https://github.com/OpenTTD/OpenGFX/issues/83) gets erroneously picked up as a OpenTTD bug 
(https://github.com/OpenTTD/OpenTTD/issues/10550)... Definitely a case of "match the original" IMO

**Comment by zephyris** [comment]
I've checked the monolev engine situation - the OpenGFX1 sprites are oversized relative to standard rail vehicle sizes, which led to them falling out of the sprite bounds. I've tweaked the source sprites to minimise the problem, but they do still overflow by one pixel in several cases. Good enough for now.
