### ISSUE TITLE
Incomplete overhead electricity lines on slopes

### ISSUE THREAD

**Issue by J-PIE-314** [zephyris/opengfx2#96]
Release: OpenGFX2 v0.4

The overhead electricity lines are incomplete when present above either of two slope directions. This is visible in 1x and 4x zoom.

Screenshots:

![opengfx2 missing line 1](https://github.com/zephyris/opengfx2/assets/80489909/72350bb9-8227-49a0-ab3a-b4621056336b)
![opengfx2 missing line 2](https://github.com/zephyris/opengfx2/assets/80489909/dbe44857-ec32-47f8-a0ce-b6a39c267cbb)

**Comment by zephyris** [comment]
Hmm, interesting... Some kind of vertical sprite size bug.
